---
- hosts: all
  become: true
  pre_tasks:

  - name: Update Ubuntu packages
    tags: config
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update Rocky packages
    tags: config
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: getuname
    tags:
      - config
      - perf
    ansible.builtin.shell: uname -r
    register: uname
    when: ansible_distribution == "Ubuntu"    

  tasks:

    - name: Install Valgrind Ubuntu
      tags: valgrind
      ansible.builtin.apt:
        name: valgrind
        state: latest
      when: ansible_distribution == "Ubuntu"
      
    - name: Install Valgrind Rocky
      tags: valgrind
      ansible.builtin.dnf:
        name: valgrind
        state: latest
      when: ansible_distribution == "Rocky"

    - name: Install perf Ubuntu
      tags: perf
      ansible.builtin.apt:
        name:
          - linux-tools-generic
          - linux-tools-{{ uname.stdout }}
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install perf Rocky
      tags: perf
      ansible.builtin.dnf:
        name: perf
        state: latest
      when: ansible_distribution == "Rocky"
