---
- hosts: all
  gather_facts: no
  pre_tasks:

  - name: Check for Cargo
    tags: config
    ansible.builtin.stat:
      path: $HOME/.cargo/env
    register: cargo_exists

  tasks:

  - name: Get Rust Setup Script
    tags: rust
    ansible.builtin.get_url:
      url: https://sh.rustup.rs
      dest: $HOME/sh.rustup.rs
      mode: '0755'
      force: yes
    when: not cargo_exists.stat.exists

  - name: install Rust and Cargo
    tags: rust
    ansible.builtin.shell: ./sh.rustup.rs -y
    when: not cargo_exists.stat.exists

  post_tasks:
  - name: remove cargo if exists
    tags: rust
    ansible.builtin.file:
      path: $HOME/sh.rustup.rs
      state: absent

